#deployment for blocksync on the akash network
#this file has not been tested
version: "2.0"

services:
  blocksync:
    image: northroomza/ixo-blocksync:latest # try to not use latest because akash uses heavy caching
    depends-on:
      - blocksync-db
    expose:
      - port: 8080
        as: 80
        accept:
          - "add.domain.hostname.here"
        to: 
          - global : true
    env:
      - 'url=https://add.the.full.domain.here'
      - PORT="8080"
      - NODE_ENV=dev
      - SENTRYDSN=
      - CHAIN_URI=
      - BC_REST=
      - IGNORE_EVENTS="message,rewards,proposer_reward,commission,mint,transfer"
      - ONLY_EVENTS=""
      - BONDS_INFO_EXTRACT_PERIOD_BLOCKS=1
      - DATABASE_URL= #postgresql://username:password@blocksync-db:5432/Blocksync?schema=public examples
      - REDIS_HOST=blocksync-qdb
      - REDIS_PORT=6379
  blocksync-grest:
    image: postgrest/postgrest:latest
    depends-on:
      - blocksync-db
    expose:
      - port: 3000
        as: 80
        accept:
          - "add.domain.hostname.here"
        to: 
          - global : true
    env:
      - 'url=https://add.the.full.domain.here'
      - PGRST_DB_URI= #postgresql://postgres:postgrespw@block-sync-db:5432/Blocksync example
      - PGRST_DB_SCHEMAS=public
      - PGRST_DB_ANON_ROLE=app_user #In production this role should not be the same as the one used for the connection
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://0.0.0.0:3000

  blocksync-qdb:
    image: redis:7.0
    depends-on:
      - blocksync-db
    env:
      - MAXMEMORY=500mb
      - DATABASES=1
      - LOGLEVEL=notice
    expose:
      - port: 6379
        as: 6379
        to: 
          - global : false

  blocksync-db:
    image: postgres:12.12
    params:
    storage:
      data: 
        moutn: /var/lib/postgres
    expose:
    - port: 5432 
      as: 5432
      to: 
        - global : false # remove and add domain url into env with domain as accept if u need to access remotely
profiles:
  compute:
    blocksync:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage: 512Mi
    blocksync-grest:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage: 512Mi
    blocksync-qdb:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage: 512Mi
    blocksync-db:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          - 512Mi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta2
  placements:
deployment: 
  blocksync:
    akash:
      profiles: blocksync
      count: 1
  blocksync-grest:
    akash:
      profiles: blocksync-grest
      count: 1
  blocksync-qdb:
    akash:
      profiles: blocksync-qdb
      count: 1
  blocksync-db:
    akash:
      profiles: blocksync-db
      count: 1
      
      ###Please note that storage only persists during the lease. The storage is lost when: 
      ###The deployment is migrated to a different provider.
      ###The deployment’s lease is closed.  Even when relaunched onto the same provider, storage will not persist across leases.