version: "3.6"
services:
  blocksync:
    container_name: blocksync
    image: ghcr.io/ixofoundation/ixo-blocksync:latest
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - blocksync-db

  blocksync-db:
    container_name: blocksync-db
    image: postgres:12.12
    restart: always
    environment:
      - POSTGRES_DB=Blocksync
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
