version: "2"
services:
  block-sync:
    container_name: block-sync
    image: trustlab/ixo-block-sync:latest
    environment:
      - PORT=
      - MONGODB_URI=
      - CHAIN_URI=
    restart: always
    links:
      - block-sync-db
      - blockchain
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
      
  block-sync-db:
    container_name: block-sync-db
    image: mongo