version: "3.6"
services:
    block-sync:
        container_name: block-sync
        image: northroomza/ixo-blocksync:latest
        env_file: .env
        restart: always
        ports:
            - 8080:8080
        links:
            - block-sync-db
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"
        depends_on:
            - block-sync-qdb
            - block-sync-db

    block-sync-grest:
        image: postgrest/postgrest:latest
        container_name: block-sync-grest
        ports:
            - 3000:3000
        environment:
            PGRST_DB_URI: postgresql://postgres:postgrespw@block-sync-db:5432/Blocksync
            PGRST_DB_SCHEMAS: public
            PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
            PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
        depends_on:
            - block-sync-db

    block-sync-qdb:
        container_name: block-sync-qdb
        image: redis:7.0
        restart: always

    block-sync-db:
        container_name: block-sync-db
        image: postgres:12.12
        restart: always
        environment:
            - POSTGRES_DB=Blocksync
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/data/db
            - ./src/prisma/migrations/20220921095458_init/:/docker-entrypoint-initdb.d/
