export enum MsgTypes {
    createProject = "/ixo.project.v1.MsgCreateProject",
    updateProjectStatus = "/ixo.project.v1.MsgUpdateProjectStatus",
    updateProjectDoc = "/ixo.project.v1.MsgUpdateProjectDoc",
    createAgent = "/ixo.project.v1.MsgCreateAgent",
    updateAgent = "/ixo.project.v1.MsgUpdateAgent",
    createClaim = "/ixo.project.v1.MsgCreateClaim",
    evaluateClaim = "/ixo.project.v1.MsgCreateEvaluation",
    withdrawFunds = "/ixo.project.v1.MsgWithdrawFunds",
    createBond = "/ixo.bonds.v1beta1.MsgCreateBond",
    editBond = "/ixo.bonds.v1beta1.MsgEditBond",
    setNextAlpha = "/ixo.bonds.v1beta1.MsgSetNextAlpha",
    updateBondState = "/ixo.bonds.v1beta1.MsgUpdateBondState",
    buy = "/ixo.bonds.v1beta1.MsgBuy",
    sell = "/ixo.bonds.v1beta1.MsgSell",
    swap = "/ixo.bonds.v1beta1.MsgSwap",
    makeOutcomePayment = "/ixo.bonds.v1beta1.MsgMakeOutcomePayment",
    withdrawShare = "/ixo.bonds.v1beta1.MsgWithdrawShare",
    withdrawReserve = "/ixo.bonds.v1beta1.MsgWithdrawReserve",
    createPaymentTemplate = "/ixo.payments.v1.MsgCreatePaymentTemplate",
    createPaymentContract = "/ixo.payments.v1.MsgCreatePaymentContract",
    createSubscription = "/ixo.payments.v1.MsgCreateSubscription",
    setPaymentContractAuthorisation = "/ixo.payments.v1.MsgSetPaymentContractAuthorisation",
    grantDiscount = "/ixo.payments.v1.MsgGrantDiscount",
    revokeDiscount = "/ixo.payments.v1.MsgRevokeDiscount",
    effectPayment = "/ixo.payments.v1.MsgEffectPayment",
}
